config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :users
  resources :sessions
  resources :comments
  root 'main#main'
  get "session_create" => 'sessions#create' , via: [:get, :post]
  delete '/logout',  to: 'sessions#destroy' , via:[:get, :post]
  get "comment_form" => 'comments#create', via: [:get, :post]
  get "create_like" => 'articles#create_like'
  get "create_dislike" => 'articles#create_dislike'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
 has_many :comments
 acts_as_votable

 def self.liked article,user
 article.liked_by user
 end

 def self.disliked article,user
  article.downvote_from user
 end

 def self.no_of_likes article
  ActsAsVotable::Vote.where(votable_id: article.id,vote_flag: true).count
 end

 def self.no_of_dislikes article
  ActsAsVotable::Vote.where(votable_id: article.id,vote_flag: false).count
 end

 def self.get_email article
  User.where(id:article.user_id).first.email
 end

end

app/models/comment.rb
class Comment < ApplicationRecord
  def self.get_comments_article article
    Comment.where(article_id:article.id)
  end

end

app/models/session.rb
class Session < ApplicationRecord
  def current_user(user_id)
    session[:user_id] = user_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @no_articles = Article.all.empty?
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to '/articles'}
        format.json { render :show, status: :created, location: @article }
        flash[:success] = "Thank You for Creating Article.."
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to '/articles'}
        format.json { render :show, status: :ok, location: @article }
        flash[:warning] = "Article Updated Successfully..."
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url}
      format.json { head :no_content }
      flash[:success] = 'Article was successfully destroyed.'
    end
  end

  def create_like
        @article = Article.where(id:params.to_unsafe_h[:format])
        @user = current_user
        Article.liked @article.first,@user
        flash[:warning] = 'Thanks for upvoting'
    redirect_to '/articles'
  end

  def create_dislike
    @article = Article.where(id:params.to_unsafe_h[:format])
    @user = current_user
    Article.disliked @article.last,@user
    flash[:danger] = "Hope we come back with good Article!Thank You for Vote."
    redirect_to '/articles'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:article_link, :article_text, :article_title, :article_description, :user_id, :is_admin)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
bp
  end

  def destroy
  end
  def index
    article_id = params.to_unsafe_h[:article_id].to_i
    comment_content  =  params.to_unsafe_h[:content]
    Comment.create(article_id: article_id,comment_body: comment_content)
    flash[:success] = 'Thank You for commenting'
    redirect_to '/articles'
  end
  def new

  end
  def show

  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def main
      if(params[:session].present?)
        user_exist= User.where(email:params[:session][:email],password:params[:session][:password]).last
        if user_exist.present?
          # creating session
          Session.create(user_id: user_exist.id,email:user_exist.email)
          flash[:success] = "Welcome to the F22 POSTS!"
          log_in user_exist.id
          redirect_to '/articles'
        else
          flash[:danger] = "Please Check Your credentials"
          redirect_to root_path
        end
      end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create

  end
  def create_session

  end

  def destroy
      log_out
      redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path}
        flash[:success] = "Thank You for Signing Up! Welcome to F22"
        flash[:danger] = "Please Signin to F22"
         format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in (user_id)
     session[:user_id] = user_id
  end

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    end
  end

  def user_signed_in
    Session.where(user_id:session[:user_id]).exists?
  end

  def log_out
    Session.where(user_id:session[:user_id]).destroy_all
    flash[:danger] = "Signed out Successfully..."
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container article_heading">
  <div class="field">
    <%= f.label :article_link %>
    <%= f.text_field :article_link,:class => "form-control", placeholder: "Enter Article Link" %>
  </div>

  <div class="field">
    <%= f.label :article_text %>
    <%= f.text_area :article_text,:class => "form-control", :placeholder => "Enter Article Text" %>
  </div>

  <div class="field">
    <%= f.label :article_title %>
    <%= f.text_area :article_title,:class => "form-control", placeholder: "Enter article title" %>
  </div>

  <div class="field">
    <%= f.label :article_description %>
    <%= f.text_field :article_description,:class => "form-control" , placeholder: "Enter Article Description" %>
    <%= f.hidden_field :user_id, :value => current_user.id%>
    <%= f.hidden_field :is_admin, :value => true %>

  </div>
  <div class="actions">
    <%= f.submit  :class => "btn btn-sm btn-dark"%>
  </div>
</div>

<% end %>

app/views/articles/edit.html.erb
<% content_for :signin do %>
  <div class="container">
    <h1 class="article_heading">Editing Article</h1>
    <%= render 'form', article: @article %>
    <%= link_to 'Show', @article %>
    <%= link_to 'Back', articles_path %>
  </div>

<% end %>

app/views/articles/index.html.erb
<% content_for :signin do %>
<p id="notice"><%= notice %></p>
<div class="container">
<h1 class="article_heading">Highlights of 2018! Welcome to 2019!!</h1>
  <% @articles.each do |article| %>
    <ul class="article_heading">
      <li>
        <div class="row title_heading">
          <a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            <div class="col-md-12">
              <b><%= article.article_title %></b>
              <br>
            </div>
          </a>
        </div>
      </li>
    </ul>
    <div class="collapse" id="collapseExample">
      <div class="card-header" style="color:white">
        <%= article.article_text %><i class="fas fa-external-link float-right" aria-hidden="true"><%= link_to 'Know More', article , class: "fas fa-external-link-square-alt" , style: "color:white;"%></i>
        <footer class="blockquote-footer article_heading">Written By <cite title="Source Title"><%= Article.get_email article %></cite></footer>
      </div>
      <div class="card card-body">
        <h5 class="card-title"><%= article.article_title %></h5>
        <%= article.article_description %>
        <%= form_tag({controller: "comments", action:"create"}, method: "get") do %>
          <div class="field">
            <div class="control">
              <%= text_area_tag :content,"" ,class:"form-control", placeholder: "Your comment on this post..." %>
              <%= hidden_field_tag :article_id ,article.id %>
            </div>
            <div class="float-right">
              <i class="fas fa-thumbs-up" style="color:green"><%= link_to "UpVote",create_like_path(article) %></i>
              <i class="fas fa-thumbs-down" style="color:red;"><%= link_to "DownVote",create_dislike_path(article) %></i>
            </div>
            <div>
                <span style="color:green">No of Upvotes:<%= Article.no_of_likes article  %></span><br>
                <span style="color: red">No of DownVotes:<%= Article.no_of_dislikes article%></span>
            </div>
            <div style="text-align: center">
              <i class=""></i><%= link_to 'See All Comments', article ,class:"fas fa-comments", style: "text-decoration:none"%>
            </div>
          </div>
          <%= submit_tag :submit, class: "btn btn-success btn-sm" %>
        <% end %>

      </div>
      <hr>
      <% if article.user_id == session[:user_id] %>
        <div class="card-footer text-muted">
          <div class="row">
            <div class="coll-md-10">
              <%= link_to 'Edit my post', edit_article_path(article),class:"btn btn-sm btn-outline-dark fas fa-edit" %>
            </div>
            <div class="col-md-2 float-right">
              <%= link_to '', article, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-sm btn-outline-danger fas fa-trash-alt" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <% end %>


<!--  NO ARTICLES MESSAGE-->
<% if @no_articles %>
    <div class="alert alert-warning" role="alert">
      <h4 class="alert-heading">Sorry!! No Artciles Come Back Later.</h4>
      <p>Thanks For Choosing F22 Articles Site....Come back Later for More Articles...!!</p>
    </div>
<% end %>
<%= link_to 'New Article', new_article_path %>
</div>
<% end %>

app/views/articles/new.html.erb
<% content_for :signin do %>
  <div class="container"><b>
  <h1 class="article_heading">Create a Article</h1>

  <%= render 'form', article: @article %>

  <%= link_to 'Back', articles_path %>
  </div>
<% end %>

app/views/articles/show.html.erb
<% content_for :signin do %>
<div class="container article_heading">
<p>
  <strong>Article link:</strong>
  <%= @article.article_link %>
</p>

<p>
  <strong>Article text:</strong>
  <%= @article.article_text %>
</p>

<p>
  <strong>Article title:</strong>
  <%= @article.article_title %>
</p>

<p>
  <strong>Article description:</strong>
  <%= @article.article_description %>
</p>
  <h1 class="center_heading">Comments for this Post..</h1>
  <% (Comment.get_comments_article @article).each do |item|%>
    <div class="card mb-3" style="color: black; font-family: monospace ;font-size: 20px;  ">
        <%= item.comment_body %>.
    </div>
  <% end %>
  <% if (Comment.get_comments_article @article).empty? %>
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">No one has commented on this article!!!....</h4>
      <p>Thanks For Choosing F22 Articles Site....Come back Later for More Comments...!!</p>
    </div>
  <% end %>
<%= link_to 'Back', articles_path %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<% if (!user_signed_in) && (params.to_unsafe_h[:controller] != 'articles') %>
<div class="container-fluid" style="background-color:#f5f5f5;position: absolute;bottom:0px;">
  <footer class="page-footer font-small">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <a href="https://www.linkedin.com/in/samala-sumanth-82431161/">Samala Sumanth</a>
    </div>
  </footer>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><%= image_tag("1181616.png", :alt => "F22", style: "height:40px;width:50px;") %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/articles">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://f22labs.com/#" target="_blank">Go to Website</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" />
      <button class="btn btn-dark btn-sm my-2 my-sm-0" type="submit">Search</button>
      <% if user_signed_in %>
      <%= link_to 'Sign out',logout_path, method: :delete, :class => "btn btn-danger btn-sm" %>
      <% end %>
    </form>
  </div>
</nav>

app/views/layouts/_show_articles.html.erb
<% content_for :signin do %>
  <div>Sumanth</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>F22</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     </head>
  <script type="text/javascript">
      particlesJS.load('particles-js','/assets/particles.json', function() {
          console.log('callback - particles.js config loaded');
      });
  </script>

  <body>
  <%= render 'layouts/navbar' %>
  <% flash.each do |key, value| %>
    <div class="container" id="particles-js" style="text-align: center;">
      <div class="row">
        <div class="col-md-12 alert alert-<%= key %>" style="width:10%;"><%= value %></div>
      </div>
    </div>
  <% end %>
  <%= yield(:signin) %>
  <%= render 'layouts/footer' %>
  </body>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

</html>

app/views/main/_show_articles.html.erb
too much

app/views/main/main.html.erb
<% content_for :signin do %>
  <style>
    #signinform {
      width:50%;
      margin-left:15rem;
      border-radius:0.5rem;
      background-color:#f5f5f5;
      box-shadow:0 1.5px 4px rgba(0,0,0,0.24), 0 1.5px 6px rgba(0,0,0,0.12);
    }
  </style>
  <div class="container">
    <form id = 'signinform'style="" class="p-5 mt-5 mb-5">
      <%= form_for :session, url:"/session_create", method:'PUT' do |f| %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.submit "Log in", class: "btn btn-outline-success mt-5", style: "color:black !important" %>
        <%= link_to "Sign Up",new_user_path,:class => "btn btn-outline-primary mt-5 ml-5", style: "color:black !important" %>
      <% end %>


    </form>
  </div>

<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> Please Check the  Entered Values</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :email,'Email Address' %>
    <%= f.text_field :email,type:"email", class:'form-control' %>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
      else.
    </small>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.text_field :password, type:"password", class:'form-control'  %>
  </div>
  <div class="actions">
    <%= f.submit 'SIGN UP', :class=> 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% content_for (:signin) do %>
  <div class="container article_heading" style="width:40%;margin-top: 6rem;">
  <h1 style="text-align: center;font-family: Helvetica Neue">Sign Up For F22</h1>
<%= render 'form', user: @user %>

<%= link_to 'Signin', root_path%>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>